In [1]:
import pandas as pd
import numpy as np

## Q). Which of these would be the correct way to create a dataframe?

- `df = pd.DataFrame([[1, 2], ["Ram", "Shyam"], ["IT", "Ops"]], columns = ["emp_id", "name", "dept"])` ❌


- `df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])`  ✅


- `df = pd.DataFrame([1, "Ram", "IT"], columns = ["emp_id", "name", "dept"])`  ❌


- `df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})`  ✅


- `df = pd.DataFrame([[1, "Ram", "IT"], [2, "Jon"], [3, "Yigrit", "ECE"]], columns = ["emp_id", "name", "dept"])`  ✅

In [43]:
df = pd.DataFrame([[1, "Ram", "IT"], [2, "Jon"], [3, "Yigrit", "ECE"]], columns = ["emp_id", "name", "dept"])

df

emp_id    name  dept
0       1     Ram    IT
1       2     Jon  None
2       3  Yigrit   ECE

## Q). Perform `pd.merge()` for given dataframes df1 and df2.

In [2]:
df1 = pd.DataFrame([["Jack","Accounting"],["Roman","Engineering"],["Steph","Engineering"]], columns=["Names","Profession"])

df2 = pd.DataFrame([["Accounting","math"],["Accounting","spreadsheet"],["Engineering","coding"],["Engineering","linux"],["HR","spreadsheet"],["HR","organization"]], columns=["Profession","skills_required"])

print(df1)
print("="*30)
print(df2)

   Names   Profession
0   Jack   Accounting
1  Roman  Engineering
2  Steph  Engineering
    Profession skills_required
0   Accounting            math
1   Accounting     spreadsheet
2  Engineering          coding
3  Engineering           linux
4           HR     spreadsheet
5           HR    organization


In [3]:
pd.merge(df1, df2)

Names   Profession skills_required
0   Jack   Accounting            math
1   Jack   Accounting     spreadsheet
2  Roman  Engineering          coding
3  Roman  Engineering           linux
4  Steph  Engineering          coding
5  Steph  Engineering           linux

****

## Q). Dataframe about customer ratings is given. Return the subset of the dataframe with records having a `rating >= 6`, containing the columns "profession", "gender" and "age" only.

In [4]:
customers = pd.DataFrame({'name':["Ruby","Anurag","Deepak"],
                          "profession":['HR manager','Doctor','Data Scientist'],
                          "gender":['female','male','male'],
                          "age":[21,20,25],
                          "review":['No comments','hardworker','need improvement'],
                          "rating":[10,5,7]})

customers

name      profession  gender  age            review  rating
0    Ruby      HR manager  female   21       No comments      10
1  Anurag          Doctor    male   20        hardworker       5
2  Deepak  Data Scientist    male   25  need improvement       7

In [5]:
customers.loc[customers["rating"] >= 6, ['profession', 'gender', 'age']]

profession  gender  age
0      HR manager  female   21
2  Data Scientist    male   25

In [6]:
import pandas as pd
student_data = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004','s001','s003'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI','IX','X'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes','Jane','Martin'],
    'age': [12, 12, 13, 13, 14, 12, 15, 20],
    'height': [173, 192, 186, 167, 151, 159, 140, 160],
    'weight': [35, 32, 33, 30, 31, 32, 40, 50]},
  index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6','S7','S8'])

student_data

school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30
S5        s002     V    Gino Mcneill   14     151      31
S6        s004    VI    David Parkes   12     159      32
S7        s001    IX            Jane   15     140      40
S8        s003     X          Martin   20     160      50

#### Code in block 'A', prints the number of observations in all the unique 'school_code' and 'class' combinations.

In [7]:
## A

grouped_data = student_data.groupby(['school_code', 'class'])
print((grouped_data.size()))

grouped_data

school_code  class
s001         IX       1
             V        1
             VI       1
s002         V        2
s003         VI       1
             X        1
s004         VI       1
dtype: int64


#### Code in block 'B', prints all the observations of each 'school_code' except the last 1 observation in each unique "school_code".

In [8]:
## B

n = 1
rows_to_drop = student_data.groupby(['school_code']).tail(n).index
result1 = student_data.drop(rows_to_drop, axis=0)

print(result1)

   school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30


In [9]:
rows_to_drop

Index(['S5', 'S6', 'S7', 'S8'], dtype='object')

In [10]:
student_data.groupby(['school_code']).tail(1)

school_code class          name  age  height  weight
S5        s002     V  Gino Mcneill   14     151      31
S6        s004    VI  David Parkes   12     159      32
S7        s001    IX          Jane   15     140      40
S8        s003     X        Martin   20     160      50

****

## Q). Find out all the rows containing one or more `NaN` values in a data frame `df`

- `df[df.isna()]`


- `df.isna()`


- `df[df.isnull().any(axis=1)]` ✅


- `df[df.isnull(axis=1)]`

In [11]:
student_data = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004','s001','s003'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI','IX','X'],
    'name': [np.NaN,'Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes','Jane','Martin'],
    'age': [12, 12, np.NaN, 13, 14, 12, 15, 20],
    'height': [np.NaN, 192, 186, 167, 151, 159, 140, 160],
    'weight': [35, 32, 33, 30, 31, 32, 40, 50]},
 index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6','S7','S8'])


student_data

school_code class          name   age  height  weight
S1        s001     V           NaN  12.0     NaN      35
S2        s002     V  Gino Mcneill  12.0   192.0      32
S3        s003    VI   Ryan Parkes   NaN   186.0      33
S4        s001    VI  Eesha Hinton  13.0   167.0      30
S5        s002     V  Gino Mcneill  14.0   151.0      31
S6        s004    VI  David Parkes  12.0   159.0      32
S7        s001    IX          Jane  15.0   140.0      40
S8        s003     X        Martin  20.0   160.0      50

In [12]:
student_data[student_data.isnull().any(axis=1)]

## also corret with `isna().any()` => student_data[student_data.isna().any(axis=1)]

school_code class         name   age  height  weight
S1        s001     V          NaN  12.0     NaN      35
S3        s003    VI  Ryan Parkes   NaN   186.0      33

****

## Q). Given a dataframe, with a single column "City/tState", return the preprocessed dataframe with names of City and State separated.

In [15]:
df = pd.DataFrame({"City\tState":['Kolkata\tWest Bengal', 'Chennai\tTamil Nadu', 'Hyderabad\tTelengana', 'Bangalore\tKarnataka']})

df

City\tState
0  Kolkata\tWest Bengal
1   Chennai\tTamil Nadu
2  Hyderabad\tTelengana
3  Bangalore\tKarnataka

In [16]:
df_new = pd.DataFrame([], [])

df_new[['City', 'State']] = df['City\tState'].str.split('\t', 1, expand=True)

## OR, try this :
# df_new = df['City\tState'].str.split('\t', expand=True)
# df_new.columns = df.columns[0].split('\t')

df_new

City        State
0    Kolkata  West Bengal
1    Chennai   Tamil Nadu
2  Hyderabad    Telengana
3  Bangalore    Karnataka

****

## Q). Given a dataframe as shown below, return the series of male names in the age group of 23-30 (inclusive of both 23 and 30).

In [17]:
df = pd.DataFrame({'name':["Mark","Ram","Dev"],
                   "profession":['dev','mle','mle'],
                   "gender":['male','male','male'],
                   "age":[21,20,30],
                   "review":['need improvement','Can be improved','Scope of improvement'],
                   "rating":[10,5,7]
                  })

df

name profession gender  age                review  rating
0  Mark        dev   male   21      need improvement      10
1   Ram        mle   male   20       Can be improved       5
2   Dev        mle   male   30  Scope of improvement       7

In [18]:
df[ (df["age"].isin(range(23,31))) & (df["gender"].isin(["male"])) ]["name"]

2    Dev
Name: name, dtype: object

****

## Q). A dataframe consists of the names and ages of a few candidates.

You need to convert `age` column into categories according to the following conditions :
1. If age<18: kid
2. age >=18 and <=50: adult
3. age>50: senior

Write a program to do so using `apply` function.

In [19]:
studs = pd.DataFrame({'name':["Ram","Shyam","Mukesh","Suresh"],'age':[10,18,60,50]})
studs

name  age
0     Ram   10
1   Shyam   18
2  Mukesh   60
3  Suresh   50

In [20]:
def replace_ages(df):
    '''a is a dataframe with columns ['name', 'age']
       Output A dataframe with same columns but with changed records as per required is expected to be returned'''

    # YOUR CODE GOES HERE

#     df["age_cat"] = df["age"].apply(apply_category)
#     df.drop(["age"], axis=1, inplace=True)
#     df.rename(columns={"age_cat":"age"}, inplace=True)
#     return df

    change   = lambda x: 'senior' if x>50 else 'adult' if x>=18 else 'kid'
    df['age'] = df["age"].apply(change)
    
    return pd.DataFrame(df, columns=['name','age'])


def apply_category(x):
    if x < 18:
        return "kid"
    elif 18 <= x <= 50:
        return "adult"
    else:
        return "senior"

In [21]:
x = replace_ages(studs)
x

name     age
0     Ram     kid
1   Shyam   adult
2  Mukesh  senior
3  Suresh   adult

In [22]:
studs

name     age
0     Ram     kid
1   Shyam   adult
2  Mukesh  senior
3  Suresh   adult

****

## Q). Return a new dataframe with the count of `ord_no` for each `salesman_id` and `customer_id` pair.

In [23]:
orders = pd.DataFrame({'ord_no'     :[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
                       'purch_amt'  : [150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
                       'ord_date'   : ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27',
                                       '2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
                       'customer_id': [3005,3001,3002,3009,3005,3007,3002,3004,3009,3008,3003,3002],
                       'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001]
                      })

orders

ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001

In [24]:
orders.groupby(["salesman_id","customer_id"])["ord_no"].count().reset_index()

salesman_id  customer_id  ord_no
0         5001         3002       3
1         5001         3007       1
2         5002         3005       2
3         5002         3008       1
4         5003         3009       2
5         5005         3001       1
6         5006         3004       1
7         5007         3003       1

## Q). Given a data frame `df`, try to form a code where you'd delete all such columns that have only 1 unique value :

In [ ]:
for col_name in df.columns:
    if df[col_name].nunique() == 1:
        df.drop(col_name, axis=1, inplace=True)


## axis = 1, because this is gonna be horizontal operation.

## Q). Given the dataframe `df` as input, do the following steps for preprocessing:

1. Remove the row if all the columns have missing values.

2. Replace the missing values of "Roll_ID" column with 0 and "Name" column with "Anonymous"

3. Replace the missing values in "Marks" column with the median value of the column

4. Change the numerical columns (Roll_ID and Marks) to int datatype in the output

In [78]:
roll_id = [412, np.NaN, 456, np.NaN, 434, 429, 418]
name = ["Thor", "Peter","Banner", np.NaN, "Nick", "Hill", np.NaN]
marks = [np.nan, 32, 25, np.NaN, 35, 28, 38]

df = pd.DataFrame({'Roll_ID':roll_id,
                   'Name':name,
                   'Marks':marks
                  })

df

Roll_ID    Name  Marks
0    412.0    Thor    NaN
1      NaN   Peter   32.0
2    456.0  Banner   25.0
3      NaN     NaN    NaN
4    434.0    Nick   35.0
5    429.0    Hill   28.0
6    418.0     NaN   38.0

In [79]:
def preprocess(df):
    """Takes df as input, do the preprocessing as asked. Return the preprocessed dataframe"""
    
    # Drop the rows with all null values
    df.dropna(how='all', inplace=True)

    # Replace the missing values of "Roll_ID" column with 0 and "Name" column with "Anonymous"
    df["Roll_ID"] = df["Roll_ID"].fillna("0")
    df["Name"]    = df["Name"].fillna("Anonymous")
    df["Marks"] = df["Marks"].astype('float')
  
    # Replace the missing values in "Marks" column with the median value of the column
    df["Marks"] = df["Marks"].fillna(df["Marks"].median())
  
    # Change the numerical columns (Roll_ID and Marks) to int datatype in the output
    df["Roll_ID"] = df["Roll_ID"].astype('int')
    df["Marks"] = df["Marks"].astype('int')

    return df

    
preprocess(df)

Roll_ID       Name  Marks
0      412       Thor     32
1        0      Peter     32
2      456     Banner     25
4      434       Nick     35
5      429       Hill     28
6      418  Anonymous     38

## Q). A dataset about sales of a certain electronics sale shop is given.

### a.) Write a Pandas program to create a Pivot table and find -> units sold for each item, per region or region-wise.

In [8]:
df = pd.DataFrame({'Region': {0: 'East', 1: 'Central', 2: 'Central', 3: 'Central', 4: 'West'},
                   'Manager': {0: 'Martha', 1: 'Hermann', 2: 'Hermann', 3: 'Timothy', 4: 'Timothy'},
                   'SalesMan': {0: 'Alexander', 1: 'Shelli', 2: 'Luis', 3: 'David', 4: 'Stephen'},
                   'Item': {0: 'Television', 1: 'Home Theater', 2: 'Television', 3: 'Cell Phone', 4: 'Television'},
                   'Units': {0: 95.0, 1: 50.0, 2: 36.0, 3: 27.0, 4: 56.0},
                   'Unit_price': {0: 1198.0, 1: 500.0, 2: 1198.0, 3: 225.0, 4: 1198.0},
                   'Sale_amt': {0: 113810.0, 1: 25000.0, 2: 43128.0, 3: 6075.0, 4: 67088.0}
                  })

df

Region  Manager   SalesMan          Item  Units  Unit_price  Sale_amt
0     East   Martha  Alexander    Television   95.0      1198.0  113810.0
1  Central  Hermann     Shelli  Home Theater   50.0       500.0   25000.0
2  Central  Hermann       Luis    Television   36.0      1198.0   43128.0
3  Central  Timothy      David    Cell Phone   27.0       225.0    6075.0
4     West  Timothy    Stephen    Television   56.0      1198.0   67088.0

In [9]:
df.pivot_table(index=["Region", "Item"],
               values="Units"
              )

Units
Region  Item               
Central Cell Phone     27.0
        Home Theater   50.0
        Television     36.0
East    Television     95.0
West    Television     56.0

### b). Show only first 5 records (from `df`) for columns - `Region`, `SalesMan`, and `Sale_amt`.

In [15]:
df.iloc[:5, [0, 2, 6]]

Region   SalesMan  Sale_amt
0     East  Alexander  113810.0
1  Central     Shelli   25000.0
2  Central       Luis   43128.0
3  Central      David    6075.0
4     West    Stephen   67088.0

### c). Show only first 5 records (from `df`) taking last 3 columns only.

In [21]:
df.iloc[:5, -3:]

Units  Unit_price  Sale_amt
0   95.0      1198.0  113810.0
1   50.0       500.0   25000.0
2   36.0      1198.0   43128.0
3   27.0       225.0    6075.0
4   56.0      1198.0   67088.0

### d). Correct code to print every row of `SalesMan` column :

- `df["SalesMan"]`  ✅


- `df.iloc[:,'disp']` ❌


- `df.loc[:, "SalesMan"]` ✅

****

## Q). How to pivot below mentioned dataframe such that each customer would have a value that is the total quantity of a particular type of accessories he holds ?

In [32]:
df = pd.DataFrame({
  "Accessories": ["Laptop", "Laptop", "Ipad", "Ipad", "Tablet", "Laptop"],
  "customer": ["Andrew", "Andrew", "Tom", "Andrew", "Tobey", "Peter"],
  "quantity": [1, 2, 2, 3, 1, 2],
})

df

Accessories customer  quantity
0      Laptop   Andrew         1
1      Laptop   Andrew         2
2        Ipad      Tom         2
3        Ipad   Andrew         3
4      Tablet    Tobey         1
5      Laptop    Peter         2

In [33]:
df.set_index(["Accessories", "customer"])["quantity"]            ## ⛔ - this mechanism is wrong. Yields incorrect output

Accessories  customer
Laptop       Andrew      1
             Andrew      2
Ipad         Tom         2
             Andrew      3
Tablet       Tobey       1
Laptop       Peter       2
Name: quantity, dtype: int64

In [34]:
df.groupby(['Accessories', 'customer']).quantity.sum()      ## ✅ - this mechanism is right! Correct output.

Accessories  customer
Ipad         Andrew      3
             Tom         2
Laptop       Andrew      3
             Peter       2
Tablet       Tobey       1
Name: quantity, dtype: int64

*****

## Q). Calculate "Date", "Month", "Year", "Day" columns.

In [37]:
reg_ids = ["498", "721", "375", "464", "813", "853", "918", "422", "380", "403", "445", "665", "43", "281", "730", "39", "63", "560"]

reg_dates = ["2015-12-06", "2011-12-27", "2015-09-07", "2012-12-21", "2020-02-13", "2015-06-09", "2013-03-21",
             "2012-09-22", "2013-06-19", "2016-03-05", "2017-08-27", "2012-06-24", "2018-11-20", "2018-05-24",
             "2019-08-17", "2018-08-22", "2021-02-07", "2016-09-01"]

In [41]:
reg_df = pd.DataFrame(zip(reg_ids, reg_dates), columns=["RID", "RDate"])

reg_df.head()

RID       RDate
0  498  2015-12-06
1  721  2011-12-27
2  375  2015-09-07
3  464  2012-12-21
4  813  2020-02-13

In [43]:
reg_df["RDate"]  = pd.to_datetime(reg_df["RDate"])
reg_df["RMonth"] = reg_df["RDate"].dt.month
reg_df["RYear"]  = reg_df["RDate"].dt.year
reg_df["RDay"]   = reg_df["RDate"].dt.day

reg_df.head()

RID      RDate  RMonth  RYear  RDay
0  498 2015-12-06      12   2015     6
1  721 2011-12-27      12   2011    27
2  375 2015-09-07       9   2015     7
3  464 2012-12-21      12   2012    21
4  813 2020-02-13       2   2020    13

****

## Q). A dataframe containing the details of students of a college with the features `['Person', 'House', 'Age', 'Books', 'Movies']`.

#### Restructure the dataframe to a long format, in such a way that the final dataframe would have features `['Person', 'House', 'variable', 'value']` where the `'variable'` will have one of {'Age', 'Books', 'Movies'} and `'value'` has the values corresponding to  these variables.

(sort the result on "Person" column, to display it clearer fashion.)

In [2]:
students = {'Person': {0: 'Alan', 1: 'Berta', 2: 'Charlie', 3: 'Danielle'},
            'House': {0: 'A-34', 1: 'A-45', 2: 'Greenwich-37', 3: 'Belador-43'},
            'Age': {0: 3, 1: 46, 2: 20, 3: 74},
            'Books': {0: 0, 1: 30, 2: 20, 3: 40},
            'Movies': {0: 0, 1: 20, 2: 80, 3: 60}
           }

students = pd.DataFrame(students)

students

Person         House  Age  Books  Movies
0      Alan          A-34    3      0       0
1     Berta          A-45   46     30      20
2   Charlie  Greenwich-37   20     20      80
3  Danielle    Belador-43   74     40      60

In [4]:
students.melt(id_vars=["Person","House"],
              value_vars=["Age","Books","Movies"]
             ).sort_values(["Person"])

Person         House variable  value
0       Alan          A-34      Age      3
4       Alan          A-34    Books      0
8       Alan          A-34   Movies      0
1      Berta          A-45      Age     46
5      Berta          A-45    Books     30
9      Berta          A-45   Movies     20
2    Charlie  Greenwich-37      Age     20
6    Charlie  Greenwich-37    Books     20
10   Charlie  Greenwich-37   Movies     80
3   Danielle    Belador-43      Age     74
7   Danielle    Belador-43    Books     40
11  Danielle    Belador-43   Movies     60

## Q). What is meaning of each operation performed with `car` dataset?

dataset : `car-sales-extended-missing-data.csv`

In [44]:
carDF = pd.read_csv("./../datasets/car-sales-extended-missing-data.csv")

carDF

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

- #### gives the number of null values in each column :

In [46]:
carDF.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

- #### gives the number of `null` values in the whole dataframe :

In [47]:
carDF.isnull().sum().sum()

249

- #### gives the number of null values in the 8th row.

In [48]:
carDF.loc[[7]].isna().sum().sum()

1

- #### gives the indices of all such rows that have atleast one `NaN` (or, `null`) in "any" column.

In [52]:
carDF[carDF.isna().any(axis=1)].index

Int64Index([  7,   8,  13,  20,  21,  31,  37,  40,  47,  51,
            ...
            957, 959, 960, 968, 972, 974, 975, 983, 985, 996],
           dtype='int64', length=227)

- #### drops all such columns that have "any" row as `null` value

In [55]:
carDF.dropna(axis=1, how='any')

## since every column has atleast 1 null. So all columns would get dropped.

- #### drop those columns that having "all" of the row-values as `NaN` only.

In [56]:
carDF.dropna(axis=1, how='all')

## since there is no column where all the rows are `null`. So, no column would drop.

- #### fill all the `NaN` values according to key, value pairs of replacement

`df.fillna(value=replacement)`

In [ ]:
carDF.fillna(value={"Make":"UNKNOWN", "Colour":"NA", "Door":"-"})

## Q). Find out the month that observed the maximum registrations?

In [57]:
df = pd.DataFrame({'Date':["2014-11-16", "2012-01-27", "2013-04-17", "2012-11-20", "2020-11-13", "2015-04-29"],
                   'RID':[1498, 7421, 1375, 4165, 8013, 8053],
                   'Phy':[72, 65, 71, 65, 52, 57],
                   'Chem':[62, 76, 72, 60, 74, 81],
                   'Math':[73, 77, 68, 72, 83, 72]
                  })

df

Date   RID  Phy  Chem  Math
0  2014-11-16  1498   72    62    73
1  2012-01-27  7421   65    76    77
2  2013-04-17  1375   71    72    68
3  2012-11-20  4165   65    60    72
4  2020-11-13  8013   52    74    83
5  2015-04-29  8053   57    81    72

In [58]:
def solve(df):
    """
    input: pandas dataframe with columns ['Date', 'RID', 'Phy', 'Chem', 'Math']
    output: pandas series
    """
    
    # code for taking input and printing output is already taken care of just return the list with required elements.
    """
        You need to return a series where the elements will be the most occuring month,
        most occuring month's frequency, average chemistry,physics and maths marks in 
        most occuring months upto two decimal places in this order.
    """
    # YOUR CODE GOES HERE

    df['Month'] = pd.to_datetime(df['Date']).dt.month_name().str[:3].str.upper()
    most_occuring_month = df['Month'].mode()[0]
    df = df[df['Month'] == most_occuring_month]

    temp = []
    max_reg_month      = (df['Month'].value_counts().idxmax()).upper()[:3]
    max_reg_month_mode = df['Month'].value_counts().max()

    temp.append(max_reg_month)
    temp.append(max_reg_month_mode)

    avgDF    = df.groupby("Month")[['Chem','Phy','Math']].mean().round(2)
    avg_list = avgDF.loc[max_reg_month, :].to_list()

    return pd.Series(temp + avg_list)

In [59]:
solve(df)

0      NOV
1        3
2    65.33
3     63.0
4     76.0
dtype: object

## Q). What's the color of point `X` ?

Assume we have some points in a 2D plane, some of which are of red color and the others are green in color.

Now we have a new point - `X`, that does not have any color.<br>
We would like to assign `X` a color (either red or green) based on the color of it's "K" nearest points.

For example, 3 of the 5 nearest points have color as red and hence we may assign the point `X` with red color.

In this process we were required to calculate the distance of point `X` from all others and pick the nearest "K" points. This algorithm is known as __K-Nearest-Neighbors__ that is a use case for calculating the distances of multiple points from a given point (in our case, `X`) efficiently.

Given that,<br>
`all_points = [[1, 2, 3, 4], [2, 3, 0, -4], [-1, 4, 1, 0], [0, 1, 2, 5], [1, 10, 0, 0], [0,0,0,0]]` ;<br>
`point_x = [4, 1, 0, 3]`

In [2]:
all_points = [[1, 2, 3, 4], [2, 3, 0, -4], [-1, 4, 1, 0], [0, 1, 2, 5], [1, 10, 0, 0], [0,0,0,0]]

point_x = [4, 1, 0, 3]

In [4]:
# Brute Force solution (#1)
distances = []
for point in all_points:
    distances.append(np.sqrt(np.sum((np.array(point_x) - np.array(point))**2)))
print(distances)

np.argsort(distances)[:5]

[4.47213595499958, 7.54983443527075, 6.6332495807108, 4.898979485566356, 9.9498743710662, 5.0990195135927845]


array([0, 3, 5, 2, 1], dtype=int64)

In [5]:
# Solution 2

In [7]:
np.tile(np.array([point_x]), (len(all_points), 1)) -  np.array(all_points)

array([[ 3, -1, -3, -1],
       [ 2, -2,  0,  7],
       [ 5, -3, -1,  3],
       [ 4,  0, -2, -2],
       [ 3, -9,  0,  3],
       [ 4,  1,  0,  3]])

In [8]:
# lets remove for loop and repeat point_x 'N' times
np.sqrt(np.sum((np.tile(np.array([point_x]), (6,1)) - np.array(all_points))**2, axis=1))

array([4.47213595, 7.54983444, 6.63324958, 4.89897949, 9.94987437,
       5.09901951])

In [9]:
# Broadcasting solution (#3)

np.sqrt(np.sum((np.array([point_x]) - np.array(all_points))**2, axis=1))

array([4.47213595, 7.54983444, 6.63324958, 4.89897949, 9.94987437,
       5.09901951])

## Q). 2D Average Pooling:

Given a 2 dimensional array of size `m x m`, and a 2 dimensional window of size `d x d`. Take the average of the elements of the 2D array that fall inside the window while moving the window by (slide=) `d` units from left-right and top-bottom.

__Eg :__

> INPUT

```python
# m=4, i.e array size = 4x4
# d=2, i.e window size = 2x2
# s=d, i.e stride=2


[[ 0,  1,  2,  3]
[ 4,  5,  6,  7]
[ 8,  9, 10, 11]
[12, 13, 14, 15]]
```

> OUTPUT

```python
[2.5, 4.5]
[10.5, 12.5]

```

In [2]:
A = np.arange(16).reshape((4,4))

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Let's extract the smaller matrices, that're bounded by sliding window :

In [3]:
np.vsplit(np.hsplit(A, 2)[0], 2)[0] # extract first part (0,0)

array([[0, 1],
       [4, 5]])

In [4]:
np.vsplit(np.hsplit(A, 2)[1], 2)[0] # extract second part (0,1)

array([[2, 3],
       [6, 7]])

#### Approach #1 :

In [5]:
result = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        result[i,j] = np.vsplit(np.hsplit(A, 2)[j], 2)[i].mean()

print(result)

# brute force solution

[[ 2.5  4.5]
 [10.5 12.5]]


#### Approach #2 :

In [13]:
splits = np.split(np.concatenate(np.split(A, 2, axis=1), axis=0), 4, axis=0)

for i in splits:
    print(i)
    print()
    print("shape => ",i.shape)
    print("-" * 50)

## only printing all smaller arrays; further below we'll calculate mean of all elements enclosed inside a smaller array

[[0 1]
 [4 5]]

shape =>  (2, 2)
--------------------------------------------------
[[ 8  9]
 [12 13]]

shape =>  (2, 2)
--------------------------------------------------
[[2 3]
 [6 7]]

shape =>  (2, 2)
--------------------------------------------------
[[10 11]
 [14 15]]

shape =>  (2, 2)
--------------------------------------------------


In [17]:
result = []
splits = np.split(np.concatenate(np.split(A, 2, axis=1), axis=0), 4, axis=0)
for split in splits:
    result.append(split.mean())

print(np.array(result).reshape(2,2).T)

## now, calculate the desired result as per above logic

[[ 2.5  4.5]
 [10.5 12.5]]


In [18]:
np.array(splits).mean(axis=0)

array([[ 5.,  6.],
       [ 9., 10.]])

In [19]:
np.array(splits).mean(axis=1)

array([[ 2.,  3.],
       [10., 11.],
       [ 4.,  5.],
       [12., 13.]])

In [20]:
np.array(splits).mean(axis=2)

array([[ 0.5,  4.5],
       [ 8.5, 12.5],
       [ 2.5,  6.5],
       [10.5, 14.5]])

In [21]:
np.array(splits).mean(axis=(1,2)).reshape(2,2).T

array([[ 2.5,  4.5],
       [10.5, 12.5]])

Let's create a generic code that calcultaes the mean of numbers falling inside a sliding window.

In [25]:
def avg_bulk(A, d=2):
    m = A.shape[0]
    # m = dimension of matrix
    # d = dimension of window
    
    ## int(m/d) => no. of parts the matrix A will get splitted into
    
    result = np.array(np.split(np.concatenate(np.split(A, int(m/d), axis=1)), int(m/d)**2)).mean(axis=(1,2))
    return result.reshape(int(m/d), int(m/d)).T

In [26]:
B = np.arange(100).reshape(10,10)

B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
avg_bulk(B)

array([[ 5.5,  7.5,  9.5, 11.5, 13.5],
       [25.5, 27.5, 29.5, 31.5, 33.5],
       [45.5, 47.5, 49.5, 51.5, 53.5],
       [65.5, 67.5, 69.5, 71.5, 73.5],
       [85.5, 87.5, 89.5, 91.5, 93.5]])

In [32]:
B = np.arange(36).reshape((6,6))

print(B)
print(B.shape)

print("=" * 20)

B_avg_bulk = avg_bulk(B)
print(B_avg_bulk)
print(B_avg_bulk.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
(6, 6)
[[ 3.5  5.5  7.5]
 [15.5 17.5 19.5]
 [27.5 29.5 31.5]]
(3, 3)


#### `avg_bulk()` function finds an application in Computer Vision, in the areas of Scaling/Rendering  higher quality (1080x720 ie. HD) image to lower quality (540x360) image.